### ISSUE TITLE
[FR] Make every collapse indicator to the right side

### ISSUE THREAD

**Issue by guihasparyk** [Galacsh/obsidian-reading-view-enhancer#10]
Hello there, that's a really awesome plugin.

I'm using Obsidian mobile on phone a lot and I'm had an idea of getting the collapsible chevron to stick to the right part of the screen. 

By any chance, do you know how to do it?

**Comment by Galacsh** [comment]
It's a bit too late, but... here is an idea.

Define your style in **Appearance > CSS snippets**.

```css
/* Some elements like headings are not relative. */
.markdown-preview-section>div:not([class="markdown-preview-pusher"]),
.markdown-preview-section>div:not([class="mod-header"]) {
    position: relative;
}

.markdown-preview-section .collapse-indicator {
    /* Stick to the right part of the screen. */
    /* Use 0 if it's okay for the indicator to overlap with the content. */
    right: -1rem;
    /* List items has additional padding. */
    padding-inline-end: 0;
}
```

Seems like it works pretty well for headings and lists.

<img width="775" alt="image" src="https://github.com/user-attachments/assets/ac38b1fb-3959-440e-b951-b758662150dd">

Since this needs to make some elements relative, that were previously not, this could lead some problems.
However, I'll try to add this feature in the next release.

Sorry for the late response.

**Comment by guihasparyk** [comment]
It's working great on Windows and Android! Thank you very much for your effort. You rock on coding.

My plan now it's to extend/adapt this code to live preview and get ride of the left margin on phone so I can get more space to read and write content, but with the functionality chevrons on the right.

**Comment by Galacsh** [comment]
Oh, now I see that this feature request was to get more space!  
I'll try it soon. :)

Thank you

**Comment by Galacsh** [comment]
For the live preview mode, try this:

**1. Collapse indicator's parent**

```css
.markdown-source-view.is-live-preview .cm-content .cm-line .cm-fold-indicator {
    float: right;
}
```

In live preview mode, using 'float' seems the easiest way to put indicator on the right side.

**2. Collapse indicator**

```css
.markdown-source-view.is-live-preview .cm-content .cm-line .cm-fold-indicator .collapse-indicator {
    /* Always show indicator. */
    opacity: 1;
    /* Some indicators has additional padding & inset at the end. */
    padding-inline-end: 0 !important;
    inset-inline-end: -1rem !important;
}
```

> [!NOTE]
> Using `!important` to override because of the [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity)

**3. Bullet/number in the list item**

```css
.markdown-source-view.is-live-preview .cm-content .cm-line .cm-formatting-list.cm-list-1,
.markdown-source-view.is-live-preview .cm-content .cm-line .cm-formatting-list.cm-list-2,
.markdown-source-view.is-live-preview .cm-content .cm-line .cm-formatting-list.cm-list-3 {
    padding-inline-start: calc(var(--list-padding-inline-start)/2);
}
```

**4. Task list item checkbox**

```css
.markdown-source-view.is-live-preview .cm-content .cm-line .task-list-item-checkbox {
    margin-inline-start: calc(var(--checkbox-margin-inline-start)/2);
}
```

**5. Indentation guide**

```css
.markdown-source-view.is-live-preview .cm-content .cm-line .cm-indent:before {
    margin-inline-start: calc(var(--indentation-guide-editing-indent)/2);
}
```

> [!IMPORTANT]
> Margin & padding of task list, list and unordered list are strongly tied.
> So, it's better to calculate than using fixed number.

---

**Before & After**

<img width="613" alt="image" src="https://github.com/user-attachments/assets/f3cbc6f1-74bb-4836-b7ff-f1268c487bb0">

---

**Full code**

```css
.markdown-source-view.is-live-preview .cm-content .cm-line .cm-fold-indicator {
    float: right;
}

.markdown-source-view.is-live-preview .cm-content .cm-line .cm-fold-indicator .collapse-indicator {
    opacity: 1;
    padding-inline-end: 0 !important;
    inset-inline-end: -1rem !important;
}

.markdown-source-view.is-live-preview .cm-content .cm-line .cm-formatting-list.cm-list-1,
.markdown-source-view.is-live-preview .cm-content .cm-line .cm-formatting-list.cm-list-2,
.markdown-source-view.is-live-preview .cm-content .cm-line .cm-formatting-list.cm-list-3 {
    padding-inline-start: calc(var(--list-padding-inline-start)/2);
}

.markdown-source-view.is-live-preview .cm-content .cm-line .task-list-item-checkbox {
    margin-inline-start: calc(var(--checkbox-margin-inline-start)/2);
}

.markdown-source-view.is-live-preview .cm-content .cm-line .cm-indent:before {
    margin-inline-start: calc(var(--indentation-guide-editing-indent)/2);
}
```

(By the way, since this plugin is for the reading view, this will not be added into the plugin.)
